### ISSUE TITLE
semantic (CEDET) symbol completions appear to right of fci's line

### ISSUE THREAD

**Issue by genovese** [alpaker/fill-column-indicator#14]
On OS X using 23.2 with the fix (changed as I described in a previously raised issue),
completion suggestions made by semantic (within the CEDET package, version 1.0)
appear to the right side of the fci produced line rather than at the end of the symbol
being completed.

I haven't had a chance yet to test this on emacs 24 to see if it is specific to 23.1-23.2,
but I'll try to do that soon.  Thought I'd let you know in any case.

Regards

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
