### ISSUE TITLE
Rule horizontal location not adjusted text-scale-adjust has been used

### ISSUE THREAD

**Issue by hoffman** [alpaker/fill-column-indicator#15]
If you use `text-scale-adjust` to make the text in a buffer larger (`C-x C-+`) or smaller (`C-x C-+`), the `fci-mode` rule stays at the same pixel location, which is no longer the same character location. This is true regardless of whether `fci-mode` is run before or after `text-scale-adjust`.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
