### ISSUE TITLE
FCI hangs on git commit on OS X 10.7

### ISSUE THREAD

**Issue by linearray** [alpaker/fill-column-indicator#20]
When performing a "git commit" from the shell with FCI globally enabled, emacs will hang. Emacs can then be interrupted with C-g, dropping me back to the shell, the process however stays around and burns 100% cpu. For all other tasks FCI works fine for me.

The symptoms are the same as described here: http://www.emacswiki.org/emacs/MarginMode

Happens with:
GNU Emacs 22.1.1 (mac-apple-darwin)
GNU Emacs 23.4.1 (x86_64-apple-darwin11.3.0)

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by glyph** [comment]
@alpaker Thanks for letting everyone know.  I hope someone takes you up on on it :)

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
