### ISSUE TITLE
Compatibility with auto-complete

### ISSUE THREAD

**Issue by root42** [alpaker/fill-column-indicator#21]
When using auto-complete, the code hints of auto-complete become garbled, like shown in the screenshot below:

![Bug triggered when using fci-mode and auto-complete](https://lh6.googleusercontent.com/-9qGyf0bZ6bQ/T_VYK1tN-eI/AAAAAAAACkk/UXcf9MeymzM/s800/fci-mode-bug-1.png)

When disabling fci-mod, the bug disappears:

![No bug when fci-mode disabled](https://lh5.googleusercontent.com/-I-Qh3vkq8ew/T_VYK2bQ3lI/AAAAAAAACko/71MVMuv5zF4/s800/fci-mode-bug-2.png)

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
