### ISSUE TITLE
Broken display when display table customised by another package

### ISSUE THREAD

**Issue by purcell** [alpaker/fill-column-indicator#27]
I just wrote [page-break-lines.el](https://github.com/purcell/page-break-lines), which modifies the display table entry for the ^L char in order to display a neat horizontal rule -- I borrowed this approach from an emacswiki article.

However, when my display table change is in effect at the same time as `fci-mode`, all the _newline_ characters are displayed as a random unicode placeholder. I think that somehow either `fci-eol-char` or `fci-blank-char` gets displayed literally. Any guesses at what might be causing this?

-Steve

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
