### ISSUE TITLE
Feature req: multiple column indicators and relative offsets

### ISSUE THREAD

**Issue by huyz** [alpaker/fill-column-indicator#29]
I could use several simultaneous rules: one for the current fill column, one for the 80 character limit (because some people and file formats insist on that) and my preferred 120 character limit.

For reference, vim 7.3 has released a column indicator option that can take an arbitrary number of columns and supports offsets from textwidth (the analog of fill-column):

https://code.google.com/p/vim/source/browse/runtime/doc/options.txt#1547

Thanks!

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
