### ISSUE TITLE
Compatibility with yasnippet

### ISSUE THREAD

**Issue by sheijk** [alpaker/fill-column-indicator#3]
Hi,

when expanding a [yas](http://code.google.com/p/yasnippet/) snippet, the rule is also not updated properly. It looks like the display property needs updating but doesn't. Editing anything in the affected lines fixes the issue. Occurred in various versions of Emacs 22 and 23, with the 0.5.3 version of yasnippet

sheijk

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
