### ISSUE TITLE
fci-mode and line-spacing

### ISSUE THREAD

**Issue by cpence** [alpaker/fill-column-indicator#36]
This may be related to #15, but if `line-spacing` is non-zero, gaps appear in the FCI between each line of text.  (I really like `(setq-default line-spacing 2)`, as it opens up the vertical display of text on the screen.)

Is there either a fix, or another way to specify looser leading that wouldn't clash with FCI?

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
