### ISSUE TITLE
FR: allow automatic enabling globally or per-mode

### ISSUE THREAD

**Issue by aspiers** [alpaker/fill-column-indicator#38]
It should be possible to `M-x customize-variable` in order to automatically enable the minor mode for all buffers, or for all buffers whose modes are in a given list.  This would work similarly to how `whitespace-mode` provides `global-whitespace-mode` and `whitespace-global-modes`.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
