### ISSUE TITLE
Display doesn't update after long movement commands

### ISSUE THREAD

**Issue by jschaf** [alpaker/fill-column-indicator#51]
If I press G to go to the last line in a file, emacs hangs until I enter some command to put me into insert mode, like `o` for `evil-open-below`.

If I disable `fci-mode`, Emacs doesn't hang when I press `G`.

The offending line of code seems to the `(search-forward "\n" end t)` at [fill-column-indicator.el#L790](https://github.com/alpaker/Fill-Column-Indicator/blob/master/fill-column-indicator.el#L790).  In my tests, it stalled right on the `while` loop test, meaning the following line was never reached.

I'm not sure why it freezes.  One workaround I found was to wrap the whole function in:

``` emacs-lisp
(when (<= start end)
  ;; rest of function
)
```

This has the unfortunate side effect of not filling in the columns, but it doesn't freeze emacs.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
