### ISSUE TITLE
Underline in commit message becomes a full line

### ISSUE THREAD

**Issue by fniessen** [alpaker/fill-column-indicator#55]
As you can see on http://screencast.com/t/aLC1c1WnFQwA, when fci-mode is enabled, the underline Under the subject of the commit message (Emacs 24.4) becomes a full line.

Minor.

**Comment by alpaker** [comment]
Thanks. Am I right in supposing that happens only when the body of the
message is empty?

**Comment by fniessen** [comment]
Thanks for answering. No, it's not only when the commit msg is empty. See http://screencast.com/t/tkofaq2Oc.

**Comment by alpaker** [comment]
This is stranger than I thought, then.  Are you able to provide a recipe
for reproducing the problem?

**Comment by fniessen** [comment]
It occurs whenever:
- fci-mode is defined as a global minor mode (as documented on EmacsWiki), or
- fci-mode is enabled in the commit message buffer.

See http://screencast.com/t/E4WhH7HL6D.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
