### ISSUE TITLE
Display troube when M-x report-emacs-bug

### ISSUE THREAD

**Issue by fniessen** [alpaker/fill-column-indicator#56]
Hello,

As you can see on http://screencast.com/t/nKckWYU40LP, the first line of the first paragraph (made up by M-x report-Emacs-bug) is moved to the right of the 80-char line.

When moving to another paragraph, the display is back to good.

When disabling fci-mode as well, back to good.

When fci-mode and putting the cursor in that first paragraph, the display trouble occurs again.

**Comment by alpaker** [comment]
I can reproduce.

I'm not sure I can fix this, though.  This might be a case where we've
reached the limits of the Emacs display engine's capabilities.  I'll do
some experiments.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
