### ISSUE TITLE
Problems in Dired mode

### ISSUE THREAD

**Issue by mrkkrp** [alpaker/fill-column-indicator#58]
Open some directory in Dired mode. Press `g` or `M-x revert-buffer`. Look at the first line that represents name of the current directory. In my case, it's shifted to the right, almost beyond screen width. It happens only when `fci-mode` is enabled.

**Comment by alpaker** [comment]
Thanks for the report.  This appears to be a regression in Emacs's display
engine's handling of cursor text properties.  I'll look into isolating the
underlying issue and filing a bug report.  I'll report back here (and close
this issue) after doing so.

**Comment by aspiers** [comment]
This only just started happening to me recently :-(

**Comment by aspiers** [comment]
I found a section entitled ["How to enabled fci-mode in text and programming modes, but not special buffers, dired, shell, etc." on emacswiki](https://www.emacswiki.org/emacs/FillColumnIndicator#toc11), but it doesn't really make sense for every user to have to manually configure fci-mode to avoid certain buffers.  It doesn't really make sense in dired mode anyway, so it would be better if it avoided buffers like that by default.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
