### ISSUE TITLE
fci-mode vs cua-mode rectangles

### ISSUE THREAD

**Issue by quarl** [alpaker/fill-column-indicator#61]
Hi,

I noticed that fci-mode messes up rectangle selection in cua-mode.

With fci-mode enabled:
![rect_with_fci](https://cloud.githubusercontent.com/assets/50023/8785279/8d41dccc-2ef4-11e5-9711-41e9bc902f95.png)

Without fci-mode:
![rect_without_fci](https://cloud.githubusercontent.com/assets/50023/8785282/91dcd9bc-2ef4-11e5-818f-7a546fca5c2a.png)

Steps to reproduce:

emacs -Q
M-x find-file fill-column-indicator.el
M-x eval-buffer
M-x fci-mode
M-4 M-8 &lt;right&gt;   ;; goto-char 49
M-x cua-mode
C-&lt;return&gt;           ;; cua-set-rectangle-mark
&lt;right&gt;&lt;right&gt;&lt;right&gt;&lt;right&gt;
M-1 M-3 down

Tested with emacs 24.3 and trunk 2015-07-17

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
