### ISSUE TITLE
Options for extending the ruler to the edge of the buffer?

### ISSUE THREAD

**Issue by Karmaflute** [alpaker/fill-column-indicator#62]
I do recognize this as a known issue:

`The indicator extends only to end of the buffer contents (as opposed to running the full length of the editing window).`

Are there any plans for this to change? I tried fill-column-indicator-legacy.el (I do prefer shading) but I get the following error when I try to enable `fci-mode` while using emacs-w32:

`Symbol's value as variable is void: fci-prior-display-table`

And this error when trying to use it in text mode:

`Symbol's value as variable is void: image-types`

This is with Emacs version 24.5.1. I understand that this is legacy code and may no longer work but I thought I'd ask just the same.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
