### ISSUE TITLE
Setting fci-ruler-character with a 5 byte unicode breaks

### ISSUE THREAD

**Issue by viccuad** [alpaker/fill-column-indicator#64]
Hi,

If I use 

```
(setq fci-rule-character ?\u1d0da)
```

which uses the `𝃚` character (see [here for an example](http://shapecatcher.com/unicode/info/119002)), Spacemacs breaks, doesn't keep reading the config (and fill-column-indicator
doesn't work).

Note that I have that character installed in my system, and I can just paste it in the buffer normally.

Cheers.

**Comment by alpaker** [comment]
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment]
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.
