### ISSUE TITLE
fci-mode obeys `fill-column` in `init.el` and nowhere else

### ISSUE THREAD

**Issue by brendes** [alpaker/Fill-Column-Indicator#84]
I'm a bit puzzled as to what's going on here. I have `fill-column` set to 80 in my `init.el`, but `fci-mode` only seems to obey this *within* `init.el`. In every other file, it fills column 70.

Meanwhile, `fci-rule-width` and my custom coloring of the ruler are obeyed everywhere.

Am I missing something obvious? Below is the relevant configuration.

```
(use-package fill-column-indicator
  :ensure t
  :config
  (setq fill-column 80)
  (setq fci-rule-width 2)
  (fci-mode)
  (bind-key "C-|" 'fci-mode))
```

* Emacs version: 25.2
* System: macOS Sierra

**Comment by alpaker** [comment]
I'm not a user of the `use-package` library, but from scanning its docs it looks as if the forms after `:config` are executed  once, after the package is loaded.   Since `fill-column` is one of those special variables that has a local value in every buffer, it looks like what you're doing is setting `fill-column` to 80 once, in whatever buffer is current at the time that form is evaluated, leaving it set to 70 (the default value) in all other buffers.  `

I think you want to either use `setq-default` to set `fill-column` for all buffers, or use the option `fci-rule-column` (which, if set, will be used by `fci-mode` instead of `fill-column`).

**Comment by brendes** [comment]
Using `setq-default` worked. Thanks so much for the help.
